// openedHours      = total age of the PR
// lastActivityHours = hours since last meaningful event (push, review, comment)
export const MOCK_PRS = [
  {
    id: 1,
    title: "feat: add OAuth2 refresh token rotation",
    branch: "feat/oauth-refresh",
    openedHours: 72,
    lastActivityHours: 60,
    author: { name: "Maya Chen", initials: "MC", hue: 210, seed: 1 },
    reviewers: [
      { name: "Tom Walsh", initials: "TW", hue: 340, seed: 3, status: "pending" },
      { name: "Sara Kim", initials: "SK", hue: 130, seed: 4, status: "approved" },
    ],
    comments: 4,
    size: "L",
    additions: 312,
    deletions: 48,
  },
  {
    id: 2,
    title: "fix: memory leak in websocket handler",
    branch: "fix/ws-memory",
    openedHours: 48,
    lastActivityHours: 6,
    author: { name: "Dev Patel", initials: "DP", hue: 45, seed: 2 },
    reviewers: [
      { name: "Maya Chen", initials: "MC", hue: 210, seed: 1, status: "changes_requested" },
    ],
    comments: 9,
    size: "S",
    additions: 23,
    deletions: 71,
  },
  {
    id: 3,
    title: "chore: upgrade webpack to v5.98",
    branch: "chore/webpack-v5",
    openedHours: 5,
    lastActivityHours: 5,
    author: { name: "Tom Walsh", initials: "TW", hue: 340, seed: 3 },
    reviewers: [
      { name: "Dev Patel", initials: "DP", hue: 45, seed: 2, status: "pending" },
      { name: "Rina Mori", initials: "RM", hue: 280, seed: 5, status: "pending" },
    ],
    comments: 1,
    size: "M",
    additions: 89,
    deletions: 12,
  },
  {
    id: 4,
    title: "feat: dark mode system preference sync",
    branch: "feat/dark-mode",
    openedHours: 38,
    lastActivityHours: 32,
    author: { name: "Sara Kim", initials: "SK", hue: 130, seed: 4 },
    reviewers: [
      { name: "Tom Walsh", initials: "TW", hue: 340, seed: 3, status: "approved" },
      { name: "Dev Patel", initials: "DP", hue: 45, seed: 2, status: "approved" },
    ],
    comments: 2,
    size: "M",
    additions: 156,
    deletions: 34,
  },
  {
    id: 5,
    title: "refactor: extract auth middleware",
    branch: "refactor/auth-mw",
    openedHours: 96,
    lastActivityHours: 90,
    author: { name: "Rina Mori", initials: "RM", hue: 280, seed: 5 },
    reviewers: [
      { name: "Sara Kim", initials: "SK", hue: 130, seed: 4, status: "pending" },
    ],
    comments: 0,
    size: "XL",
    additions: 487,
    deletions: 203,
  },
];
